select * from customer limit 20;
ALTER TABLE customer RENAME COLUMN "Customer ID" TO customer_id;

ALTER TABLE customer RENAME COLUMN "Age" TO age;

ALTER TABLE customer RENAME COLUMN "Gender" TO gender;

ALTER TABLE customer RENAME COLUMN "Item Purchased" TO item_purchased;

ALTER TABLE customer RENAME COLUMN "Category" TO category;

ALTER TABLE customer RENAME COLUMN "Purchase Amount (USD)" TO purchase_amount;

ALTER TABLE customer RENAME COLUMN "Location" TO location;

ALTER TABLE customer RENAME COLUMN "Size" TO size;

ALTER TABLE customer RENAME COLUMN "Color" TO color;

ALTER TABLE customer RENAME COLUMN "Season" TO season;

ALTER TABLE customer RENAME COLUMN "Review Rating" TO review_rating;

ALTER TABLE customer RENAME COLUMN "Subscription Status" TO subscription_status;

ALTER TABLE customer RENAME COLUMN "Shipping Type" TO shipping_type;

ALTER TABLE customer RENAME COLUMN "Discount Applied" TO discount_applied;

ALTER TABLE customer RENAME COLUMN "Promo Code Used" TO promo_code_used;

ALTER TABLE customer RENAME COLUMN "Previous Purchases" TO previous_purchases;

ALTER TABLE customer RENAME COLUMN "Payment Method" TO payment_method;

ALTER TABLE customer RENAME COLUMN "Frequency of Purchases" TO frequency_of_purchases;
----Q1. What is the total revenue generated by male vs female ?
select gender, SUM(purchase_amount)as revenue 
from customer
group by gender
---Q2. which customer used a discount but still spent more than the average purchase amount?
select customer_id,purchase_amount
from customer
where discount_applied = 'yes' and purchase_amount >= (select AVG(purchase_amount)from customer)

----Q3.Which are the top 5 products with the highest average review rating?
select item_purchased ,ROUND(AVG(review_rating::numeric),2)as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating)desc
limit 5;

----Q4.Compare the average Purchase Amount between Standard and express shipping.
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type
----Q5. Do subscribed customer spend more?Compare average spend and total revenue between subscriber and non subscribers
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue 
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

----Q6.which 5 product have the highest percentage of purchases with discounts applied ?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;
---Q7.Segment customers into new ,returning and loyal based on their total number of previous purchases and show the count of each segment. 
with customer_type as (
select customer_id,previous_purchases ,
CASE
    WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE'Loyal'
	END AS customer_segment
from customer
)
select customer_segment ,count(*) as "Number of Customer "
from customer_type
group by customer_segment
--Q8. What are the top 3 most purchased products within each catagory?
with item_counts as (
select category,
item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER()over(partition by category  order by count(customer_id)DESC) as item_rank
from customer
group by category,item_purchased
)
Select item_rank,category,item_purchased,total_orders
from item_counts
where item_rank<=3;
---Q9. are customers who are repeat buyers (more than 5 previous purchase)also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

----Q10. What is the revenue contribution of each age group?
SELECT 
CASE
    WHEN age <= 25 THEN 'Young Adult'
    WHEN age BETWEEN 26 AND 40 THEN 'Adult'
    WHEN age BETWEEN 41 AND 55 THEN 'Middle-aged'
    ELSE 'Senior'
END AS age_group,
SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;
 
